package com.lmx.xiaoxuanagent.agent

data class AgentToolDescriptor(
    val name: String,
    val type: AgentActionToolType,
    val title: String,
    val keywords: List<String> = emptyList(),
    val irreversible: Boolean = false,
    val concurrencySafe: Boolean = false,
    val requiresUserInteraction: Boolean = false,
    val shouldDefer: Boolean = false,
    val alwaysLoad: Boolean = false,
    val permissionFamily: String = "general",
    val interruptBehavior: String = "cancel",
    val inputContract: String = "",
    val resultContract: String = "",
    val progressLabel: String = "",
    val fallbackTools: List<String> = emptyList(),
    val summary: String = "",
)

object AgentToolCatalog {
    private val descriptors =
        listOf(
            AgentToolDescriptor("gui.click", AgentActionToolType.GUI, "点击节点", keywords = listOf("tap", "open"), requiresUserInteraction = true, alwaysLoad = true, inputContract = "element_id", resultContract = "页面变化或动作反馈", progressLabel = "点击节点", fallbackTools = listOf("semantic.open_best_candidate", "gui.tap_point"), summary = "点击当前 observation 中的 element_id。"),
            AgentToolDescriptor("gui.set_text", AgentActionToolType.GUI, "写入文本", keywords = listOf("input", "text"), requiresUserInteraction = true, alwaysLoad = true, permissionFamily = "write_input", inputContract = "editable element_id + text", resultContract = "节点文本被更新", progressLabel = "写入文本", fallbackTools = listOf("semantic.populate_primary_input"), summary = "直接向指定节点写入文本。"),
            AgentToolDescriptor("gui.scroll", AgentActionToolType.GUI, "滚动容器", keywords = listOf("scroll", "list"), requiresUserInteraction = true, alwaysLoad = true, inputContract = "scrollable element_id or screen", resultContract = "候选列表前进", progressLabel = "滚动页面", fallbackTools = listOf("semantic.scroll_for_more", "gui.swipe"), summary = "对指定容器或页面执行滚动。"),
            AgentToolDescriptor("gui.long_click", AgentActionToolType.GUI, "长按节点", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_long_press", inputContract = "element_id", resultContract = "上下文菜单或动作触发", progressLabel = "长按目标", fallbackTools = listOf("gui.click"), summary = "对指定节点执行长按。"),
            AgentToolDescriptor("gui.tap_point", AgentActionToolType.GUI, "点击坐标", keywords = listOf("fallback"), requiresUserInteraction = true, inputContract = "screen coordinate", resultContract = "低置信度页面变化", progressLabel = "点击坐标", fallbackTools = listOf("gui.click"), summary = "仅在节点树不足时使用的点位点击。"),
            AgentToolDescriptor("gui.swipe", AgentActionToolType.GUI, "手势滑动", keywords = listOf("gesture"), requiresUserInteraction = true, inputContract = "gesture points", resultContract = "低置信度滚动或导航", progressLabel = "执行滑动手势", fallbackTools = listOf("gui.scroll"), summary = "仅在节点树不足时使用的手势滑动。"),
            AgentToolDescriptor("gui.press_enter", AgentActionToolType.GUI, "输入法确认", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_submit", inputContract = "focused input", resultContract = "输入被提交", progressLabel = "提交输入", fallbackTools = listOf("semantic.submit_primary_action"), summary = "提交输入框当前内容。"),
            AgentToolDescriptor("system.launch_app", AgentActionToolType.SYSTEM, "启动应用", keywords = listOf("open app"), concurrencySafe = true, alwaysLoad = true, inputContract = "package_name", resultContract = "目标 App 前台激活", progressLabel = "启动应用", fallbackTools = listOf("semantic.return_to_target_app"), summary = "切到目标应用。"),
            AgentToolDescriptor("system.back", AgentActionToolType.SYSTEM, "系统返回", concurrencySafe = true, alwaysLoad = true, inputContract = "none", resultContract = "导航栈回退", progressLabel = "执行返回", fallbackTools = listOf("semantic.navigate_back"), summary = "执行系统返回。"),
            AgentToolDescriptor("system.home", AgentActionToolType.SYSTEM, "回到桌面", concurrencySafe = true, inputContract = "none", resultContract = "系统桌面前台", progressLabel = "回到桌面", summary = "执行系统 Home。"),
            AgentToolDescriptor("system.notifications", AgentActionToolType.SYSTEM, "展开通知栏", concurrencySafe = true, inputContract = "none", resultContract = "通知栏可见", progressLabel = "展开通知栏", summary = "打开通知栏。"),
            AgentToolDescriptor("system.quick_settings", AgentActionToolType.SYSTEM, "展开快捷设置", concurrencySafe = true, inputContract = "none", resultContract = "快捷设置可见", progressLabel = "展开快捷设置", summary = "打开快捷设置。"),
            AgentToolDescriptor("system.recents", AgentActionToolType.SYSTEM, "最近任务", concurrencySafe = true, inputContract = "none", resultContract = "最近任务页可见", progressLabel = "打开最近任务", summary = "切到最近任务页面。"),
            AgentToolDescriptor("system.open_settings", AgentActionToolType.SYSTEM, "打开系统设置", keywords = listOf("settings", "permission"), concurrencySafe = true, permissionFamily = "open_settings", inputContract = "settings destination", resultContract = "系统设置页打开", progressLabel = "打开系统设置", fallbackTools = listOf("system.launch_app"), summary = "直接打开系统设置子页面。"),
            AgentToolDescriptor("system.share_text", AgentActionToolType.SYSTEM, "系统分享文本", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_share", inputContract = "non-empty text", resultContract = "分享面板拉起", progressLabel = "发起系统分享", summary = "发起 Android 系统分享。"),
            AgentToolDescriptor("system.create_alarm", AgentActionToolType.SYSTEM, "创建闹钟", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_create_alarm", inputContract = "time + message", resultContract = "闹钟页打开或闹钟创建", progressLabel = "创建闹钟", summary = "通过系统闹钟创建提醒。"),
            AgentToolDescriptor("system.create_timer", AgentActionToolType.SYSTEM, "创建计时器", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_create_timer", inputContract = "duration + optional message", resultContract = "计时器页打开或计时器创建", progressLabel = "创建计时器", summary = "通过系统时钟创建计时器。"),
            AgentToolDescriptor("system.open_stopwatch", AgentActionToolType.SYSTEM, "打开秒表", concurrencySafe = true, permissionFamily = "open_stopwatch", inputContract = "none", resultContract = "时钟秒表页打开", progressLabel = "打开秒表", summary = "打开系统时钟的秒表界面。"),
            AgentToolDescriptor("system.insert_calendar_event", AgentActionToolType.SYSTEM, "创建日历事件", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_calendar_write", inputContract = "title + details", resultContract = "日历事件页打开或创建", progressLabel = "创建日程", summary = "通过系统日历创建日程。"),
            AgentToolDescriptor("system.dial_number", AgentActionToolType.SYSTEM, "拨号", keywords = listOf("call", "dial", "phone"), requiresUserInteraction = true, permissionFamily = "dial_number", inputContract = "number + optional contact_name", resultContract = "拨号盘或通话界面拉起", progressLabel = "拨号", summary = "打开系统拨号，准备拨打号码。"),
            AgentToolDescriptor("system.draft_sms", AgentActionToolType.SYSTEM, "短信草稿", keywords = listOf("sms", "message", "text"), requiresUserInteraction = true, permissionFamily = "draft_sms", inputContract = "recipient phone/contact_name + optional body", resultContract = "短信草稿界面拉起", progressLabel = "打开短信草稿", summary = "通过系统短信创建预填收件人和正文的草稿。"),
            AgentToolDescriptor("system.lookup_contact", AgentActionToolType.SYSTEM, "查找联系人", keywords = listOf("contact", "phone", "sms", "call"), concurrencySafe = true, permissionFamily = "contact_read", inputContract = "contact_name or phone fragment + optional limit", resultContract = "联系人电话候选摘要", progressLabel = "查找联系人", fallbackTools = listOf("system.open_settings", "semantic.return_to_target_app"), summary = "按姓名或号码片段读取本机联系人候选，用于拨号和短信任务。"),
            AgentToolDescriptor("system.read_sms", AgentActionToolType.SYSTEM, "读取短信", keywords = listOf("sms", "message", "otp", "inbox"), concurrencySafe = true, permissionFamily = "sms_read", inputContract = "optional sender/body query + box + limit", resultContract = "最近短信摘要和脱敏正文预览", progressLabel = "读取短信", fallbackTools = listOf("system.read_notifications", "system.open_settings"), summary = "读取本机最近短信摘要，用于短信收件箱、验证码提示和通信跟进任务。"),
            AgentToolDescriptor("system.read_call_log", AgentActionToolType.SYSTEM, "读取通话记录", keywords = listOf("call log", "missed call", "phone"), concurrencySafe = true, permissionFamily = "call_log_read", inputContract = "optional contact/name/number query + type + limit", resultContract = "最近通话记录摘要", progressLabel = "读取通话记录", fallbackTools = listOf("system.lookup_contact", "system.open_settings"), summary = "读取本机最近通话记录摘要，用于未接来电和通信跟进任务。"),
            AgentToolDescriptor("system.read_notifications", AgentActionToolType.SYSTEM, "读取通知", keywords = listOf("notification", "inbox", "reply"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "notification_read", inputContract = "optional package_name + limit", resultContract = "当前活跃通知摘要", progressLabel = "读取通知", fallbackTools = listOf("system.notifications"), summary = "读取通知监听器可见的活跃通知摘要。"),
            AgentToolDescriptor("system.reply_notification", AgentActionToolType.SYSTEM, "回复通知", keywords = listOf("notification", "reply", "message"), irreversible = true, requiresUserInteraction = true, permissionFamily = "notification_reply", inputContract = "notification_key + reply_text + optional action_hint", resultContract = "向支持 RemoteInput 的通知回复", progressLabel = "回复通知", fallbackTools = listOf("system.read_notifications", "semantic.return_to_target_app"), summary = "直接对支持回复的通知发送回复内容。"),
            AgentToolDescriptor("system.media_control", AgentActionToolType.SYSTEM, "媒体控制", keywords = listOf("music", "media", "pause"), concurrencySafe = true, permissionFamily = "media_control", inputContract = "command(play/pause/toggle/next/previous/stop)", resultContract = "媒体会话收到控制命令", progressLabel = "控制媒体", summary = "控制当前系统媒体播放会话。"),
            AgentToolDescriptor("system.adjust_volume", AgentActionToolType.SYSTEM, "调节音量", keywords = listOf("volume", "sound", "ringer"), concurrencySafe = true, permissionFamily = "volume_control", inputContract = "direction + stream + optional step", resultContract = "系统音量被调节", progressLabel = "调节音量", summary = "调节媒体、铃声或通知音量。"),
            AgentToolDescriptor("system.open_device_panel", AgentActionToolType.SYSTEM, "打开设备控制面板", keywords = listOf("wifi", "bluetooth", "network", "flashlight"), concurrencySafe = true, permissionFamily = "device_panel", inputContract = "panel(internet/bluetooth/wifi/nfc/torch/volume)", resultContract = "系统控制面板或设置页打开", progressLabel = "打开设备控制面板", fallbackTools = listOf("system.quick_settings", "system.open_settings"), summary = "打开网络、蓝牙、NFC、手电等系统控制面板。"),
            AgentToolDescriptor("system.read_device_status", AgentActionToolType.SYSTEM, "读取设备状态", keywords = listOf("wifi", "bluetooth", "battery", "brightness", "dnd"), concurrencySafe = true, permissionFamily = "device_status_read", inputContract = "target(wifi/bluetooth/nfc/flashlight/brightness/battery/dnd/overview)", resultContract = "设备能力当前状态摘要", progressLabel = "读取设备状态", fallbackTools = listOf("system.open_device_panel"), summary = "读取网络、蓝牙、NFC、亮度、电量、免打扰等设备状态。"),
            AgentToolDescriptor("system.read_current_location", AgentActionToolType.SYSTEM, "读取当前位置", keywords = listOf("location", "gps", "nearby", "map"), concurrencySafe = true, permissionFamily = "location_read", inputContract = "optional max_age_minutes", resultContract = "最近可用定位坐标、精度和新鲜度", progressLabel = "读取当前位置", fallbackTools = listOf("system.open_device_panel", "system.open_settings"), summary = "读取系统最近可用定位，用于附近、地图和到达类任务。"),
            AgentToolDescriptor("system.set_brightness", AgentActionToolType.SYSTEM, "设置亮度", keywords = listOf("brightness", "screen"), concurrencySafe = true, permissionFamily = "brightness_control", inputContract = "level(low/medium/high or percent)", resultContract = "亮度被直接设置或打开授权页", progressLabel = "设置亮度", fallbackTools = listOf("system.read_device_status", "system.open_device_panel"), summary = "在系统允许时直接设置屏幕亮度，否则引导到授权页。"),
            AgentToolDescriptor("system.set_do_not_disturb", AgentActionToolType.SYSTEM, "设置免打扰", keywords = listOf("dnd", "do not disturb", "免打扰"), concurrencySafe = true, permissionFamily = "dnd_control", inputContract = "mode(on/off/priority/alarms)", resultContract = "免打扰被直接设置或打开授权页", progressLabel = "设置免打扰", fallbackTools = listOf("system.read_device_status", "system.open_settings"), summary = "在系统允许时直接设置免打扰，否则引导到授权页。"),
            AgentToolDescriptor("system.set_battery_saver", AgentActionToolType.SYSTEM, "设置省电模式", keywords = listOf("battery saver", "省电", "低电量"), concurrencySafe = true, permissionFamily = "battery_saver_control", inputContract = "mode(on/off)", resultContract = "省电模式状态或系统电池设置页", progressLabel = "设置省电模式", fallbackTools = listOf("system.read_device_status", "system.open_device_panel"), summary = "在第三方应用可控范围内读取并引导调整省电模式。"),
            AgentToolDescriptor("system.open_power_dialog", AgentActionToolType.SYSTEM, "打开电源对话框", keywords = listOf("restart", "shutdown", "power"), concurrencySafe = true, permissionFamily = "power_dialog", inputContract = "none", resultContract = "系统电源对话框打开", progressLabel = "打开电源对话框", fallbackTools = listOf("system.home"), summary = "打开系统电源对话框，让用户继续选择重启或关机。"),
            AgentToolDescriptor("system.capture_screenshot", AgentActionToolType.SYSTEM, "记录屏幕截图", keywords = listOf("screenshot", "capture", "evidence"), concurrencySafe = true, permissionFamily = "capture_screenshot", inputContract = "optional note", resultContract = "当前观测截图被保存为 artifact", progressLabel = "记录屏幕截图", fallbackTools = listOf("platform.search_artifacts"), summary = "把当前观测截图固化成 planning_screenshot artifact。"),
            AgentToolDescriptor("system.capture_photo", AgentActionToolType.SYSTEM, "打开拍照", keywords = listOf("camera", "photo", "capture"), requiresUserInteraction = true, permissionFamily = "camera_capture", inputContract = "optional note", resultContract = "系统相机拍照界面打开", progressLabel = "打开拍照", fallbackTools = listOf("system.launch_app"), summary = "打开系统相机进行拍照。"),
            AgentToolDescriptor("online.clipboard_copy", AgentActionToolType.ONLINE, "复制文本", concurrencySafe = true, permissionFamily = "clipboard_read", inputContract = "element_id", resultContract = "剪贴板写入", progressLabel = "复制文本", summary = "复制节点文本到剪贴板。"),
            AgentToolDescriptor("online.clipboard_paste", AgentActionToolType.ONLINE, "粘贴剪贴板", irreversible = true, requiresUserInteraction = true, permissionFamily = "clipboard_write", inputContract = "editable element_id", resultContract = "目标节点写入剪贴板内容", progressLabel = "粘贴内容", fallbackTools = listOf("gui.set_text"), summary = "把剪贴板粘贴到目标节点。"),
            AgentToolDescriptor("platform.read_session_history", AgentActionToolType.ONLINE, "读取会话历史", keywords = listOf("history", "previous", "session"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "history_read", inputContract = "optional query", resultContract = "最近或命中的 session history", progressLabel = "读取会话历史", fallbackTools = listOf("platform.read_session_notebook", "platform.search_artifacts"), summary = "读取最近会话，或按 query 搜索历史任务。"),
            AgentToolDescriptor("platform.search_artifacts", AgentActionToolType.ONLINE, "检索产物证据", keywords = listOf("artifact", "evidence", "result"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "artifact_read", inputContract = "query + optional artifact_type", resultContract = "命中的 artifact 摘要与预览", progressLabel = "检索产物证据", fallbackTools = listOf("platform.read_session_history", "platform.read_session_notebook"), summary = "从 artifact 索引中检索当前或历史证据。"),
            AgentToolDescriptor("platform.recall_memory", AgentActionToolType.ONLINE, "召回长期记忆", keywords = listOf("memory", "recall", "preference"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "memory_read", inputContract = "query", resultContract = "命中的长期记忆与偏好", progressLabel = "召回长期记忆", fallbackTools = listOf("platform.read_session_notebook", "platform.read_session_history"), summary = "按 query 召回个人长期记忆、偏好、结果经验。"),
            AgentToolDescriptor("platform.read_session_notebook", AgentActionToolType.ONLINE, "读取会话笔记", keywords = listOf("notebook", "session note"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "session_notebook_read", inputContract = "none", resultContract = "当前 session notebook 摘要与预览", progressLabel = "读取会话笔记", fallbackTools = listOf("platform.recall_memory", "platform.read_session_history"), summary = "读取当前会话的 notebook/checkpoint。"),
            AgentToolDescriptor("platform.write_session_note", AgentActionToolType.ONLINE, "写入会话笔记", keywords = listOf("note", "remember", "write"), irreversible = true, concurrencySafe = true, permissionFamily = "session_notebook_write", inputContract = "note + optional tag", resultContract = "当前 session notebook 追加一条结构化笔记", progressLabel = "写入会话笔记", fallbackTools = listOf("platform.read_session_notebook"), summary = "把中间结论或人工整理结果写入当前 session notebook。"),
            AgentToolDescriptor("platform.search_tools", AgentActionToolType.ONLINE, "检索工具能力", keywords = listOf("tool", "capability", "search"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "tool_catalog_read", inputContract = "query", resultContract = "命中的 tool catalog 与 contract 线索", progressLabel = "检索工具能力", fallbackTools = listOf("platform.read_todo_board", "platform.read_session_notebook"), summary = "按任务意图在本地 tool catalog 中检索更合适的能力。"),
            AgentToolDescriptor("platform.web_search", AgentActionToolType.ONLINE, "网页搜索", keywords = listOf("web", "search", "lookup"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "web_search", inputContract = "query", resultContract = "网页搜索结果摘要", progressLabel = "执行网页搜索", fallbackTools = listOf("platform.web_fetch", "platform.search_artifacts"), summary = "当当前 observation 不足时，去公网检索补充信息。"),
            AgentToolDescriptor("platform.web_fetch", AgentActionToolType.ONLINE, "抓取网页内容", keywords = listOf("fetch", "url", "page"), concurrencySafe = true, permissionFamily = "web_fetch", inputContract = "absolute url", resultContract = "网页标题与正文摘要", progressLabel = "抓取网页内容", fallbackTools = listOf("platform.web_search"), summary = "读取指定 URL 的网页正文摘要。"),
            AgentToolDescriptor("connected.read_app_capabilities", AgentActionToolType.ONLINE, "读取 Connected App 能力", keywords = listOf("connected app", "capability", "app action"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "connected_app_read", inputContract = "optional app_id", resultContract = "本地 connected app 的结构化能力目录", progressLabel = "读取 Connected App 能力", fallbackTools = listOf("platform.search_tools"), summary = "读取本地已接入 connected app 的结构化操作能力。"),
            AgentToolDescriptor("connected.execute_app_action", AgentActionToolType.ONLINE, "执行 Connected App 动作", keywords = listOf("connected app", "structured action", "intent"), concurrencySafe = true, permissionFamily = "connected_app_execute", inputContract = "app_id + operation + optional primary/secondary/note", resultContract = "通过结构化 connector 或 Intent 执行 App 动作", progressLabel = "执行 Connected App 动作", fallbackTools = listOf("connected.read_app_capabilities", "system.launch_app", "semantic.return_to_target_app"), summary = "优先通过 structured app connector，而不是直接走 GUI 自动化。"),
            AgentToolDescriptor("platform.read_todo_board", AgentActionToolType.ONLINE, "读取 Todo Board", keywords = listOf("todo", "checklist", "plan"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "todo_read", inputContract = "none", resultContract = "当前 session 的 todo 列表", progressLabel = "读取 Todo Board", fallbackTools = listOf("platform.read_session_notebook"), summary = "读取当前 session 的 todo/checklist。"),
            AgentToolDescriptor("platform.write_todo_board", AgentActionToolType.ONLINE, "写入 Todo Board", keywords = listOf("todo", "checklist", "plan"), irreversible = true, concurrencySafe = true, permissionFamily = "todo_write", inputContract = "multi-line todo + mode", resultContract = "当前 session todo 列表被更新", progressLabel = "写入 Todo Board", fallbackTools = listOf("platform.read_todo_board", "platform.write_session_note"), summary = "把当前计划、待办或 worker checklist 写入 session todo board。"),
            AgentToolDescriptor("platform.delegate_local_agent", AgentActionToolType.ONLINE, "委派本地 Worker", keywords = listOf("delegate", "worker", "subtask"), irreversible = true, concurrencySafe = true, permissionFamily = "delegate_worker", inputContract = "task + optional summary + optional role(general/explore/plan/verification)", resultContract = "本地 worker/subagent 已排队", progressLabel = "委派本地 Worker", fallbackTools = listOf("platform.read_worker_roles", "platform.write_todo_board", "platform.write_session_note"), summary = "把子任务委派给本地 worker 队列执行。"),
            AgentToolDescriptor("platform.read_worker_roles", AgentActionToolType.ONLINE, "读取 Worker 角色", keywords = listOf("worker", "role", "agent"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "worker_role_read", inputContract = "none", resultContract = "内建 worker 角色目录", progressLabel = "读取 Worker 角色", fallbackTools = listOf("platform.search_tools"), summary = "读取本地内建 worker/subagent 角色。"),
            AgentToolDescriptor("platform.read_worker_mailbox", AgentActionToolType.ONLINE, "读取 Worker Mailbox", keywords = listOf("worker", "mailbox", "approval"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "worker_mailbox_read", inputContract = "optional target + include_consumed + limit", resultContract = "worker partial result / approval / control 消息", progressLabel = "读取 Worker Mailbox", fallbackTools = listOf("platform.read_todo_board", "platform.read_session_history"), summary = "读取当前 session 或指定 worker/session 的 mailbox 消息。"),
            AgentToolDescriptor("platform.reply_worker_message", AgentActionToolType.ONLINE, "回复 Worker 消息", keywords = listOf("worker", "reply", "approve"), irreversible = true, concurrencySafe = true, permissionFamily = "worker_mailbox_reply", inputContract = "message_id + optional decision + note", resultContract = "对 mailbox 消息的回信或权限响应已发送", progressLabel = "回复 Worker 消息", fallbackTools = listOf("platform.read_worker_mailbox"), summary = "对 worker mailbox 的 partial result / permission request / control 消息做回复。"),
            AgentToolDescriptor("platform.ack_worker_message", AgentActionToolType.ONLINE, "确认 Worker 消息", keywords = listOf("worker", "mailbox", "ack"), irreversible = true, concurrencySafe = true, permissionFamily = "worker_mailbox_ack", inputContract = "message_id + optional note", resultContract = "mailbox 消息被显式确认", progressLabel = "确认 Worker 消息", fallbackTools = listOf("platform.read_worker_mailbox"), summary = "显式确认已经消费的 worker mailbox 消息，避免重复打断。"),
            AgentToolDescriptor("platform.read_session_memory_file", AgentActionToolType.ONLINE, "读取 Session Memory File", keywords = listOf("memory", "current state", "continuity"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "session_memory_file_read", inputContract = "none", resultContract = "当前 session continuity file 摘要", progressLabel = "读取 Session Memory File", fallbackTools = listOf("platform.read_session_notebook", "platform.read_session_history"), summary = "读取当前 session 的 continuity memory file。"),
            AgentToolDescriptor("platform.read_worker_status", AgentActionToolType.ONLINE, "读取 Worker 状态", keywords = listOf("worker", "status", "join"), concurrencySafe = true, alwaysLoad = true, permissionFamily = "worker_status_read", inputContract = "optional worker/session target", resultContract = "worker 状态、join、result 摘要", progressLabel = "读取 Worker 状态", fallbackTools = listOf("platform.read_worker_mailbox"), summary = "读取本地 worker 的状态、join 情况和子 worker 摘要。"),
            AgentToolDescriptor("platform.merge_worker_result", AgentActionToolType.ONLINE, "合并 Worker 结果", keywords = listOf("worker", "merge", "result"), irreversible = true, concurrencySafe = true, permissionFamily = "worker_result_merge", inputContract = "message_id + optional note", resultContract = "worker 结果被写入 notebook 并确认", progressLabel = "合并 Worker 结果", fallbackTools = listOf("platform.read_worker_mailbox", "platform.read_worker_status"), summary = "把 worker mailbox 结果收口进主线程记忆，并确认消息。"),
            AgentToolDescriptor("semantic.focus_primary_input", AgentActionToolType.SEMANTIC, "聚焦主输入框", keywords = listOf("focus input"), alwaysLoad = true, inputContract = "current observation", resultContract = "主输入框获得焦点", progressLabel = "聚焦主输入框", fallbackTools = listOf("gui.click"), summary = "把焦点拉回主输入框。"),
            AgentToolDescriptor("semantic.populate_primary_input", AgentActionToolType.SEMANTIC, "填充主输入框", keywords = listOf("search", "type"), alwaysLoad = true, permissionFamily = "write_input", inputContract = "text", resultContract = "主输入框完成文本填充", progressLabel = "填充主输入框", fallbackTools = listOf("gui.set_text", "online.clipboard_paste"), summary = "对主输入框执行稳定文本填充。"),
            AgentToolDescriptor("semantic.submit_primary_action", AgentActionToolType.SEMANTIC, "触发主提交", irreversible = true, requiresUserInteraction = true, permissionFamily = "confirm_submit", inputContract = "submit hint", resultContract = "搜索/发送/确认被触发", progressLabel = "触发主提交", fallbackTools = listOf("gui.press_enter", "gui.click"), summary = "执行搜索/发送/确认等主提交动作。"),
            AgentToolDescriptor("semantic.dismiss_interrupt", AgentActionToolType.SEMANTIC, "关闭中断层", alwaysLoad = true, permissionFamily = "dismiss_interrupt", inputContract = "current interrupt hints", resultContract = "弹窗或遮罩被关闭", progressLabel = "关闭中断层", fallbackTools = listOf("gui.click", "system.back"), summary = "关闭弹窗、权限提示或遮罩。"),
            AgentToolDescriptor("semantic.open_best_candidate", AgentActionToolType.SEMANTIC, "打开最匹配候选", shouldDefer = true, inputContract = "target_text + role_hint", resultContract = "匹配候选被打开", progressLabel = "打开候选目标", fallbackTools = listOf("gui.click", "semantic.scroll_for_more"), summary = "在候选列表中选择最相关目标。"),
            AgentToolDescriptor("semantic.scroll_for_more", AgentActionToolType.SEMANTIC, "继续探索", shouldDefer = true, inputContract = "direction", resultContract = "更多候选进入视野", progressLabel = "继续探索页面", fallbackTools = listOf("gui.scroll"), summary = "为找更多候选而滚动。"),
            AgentToolDescriptor("semantic.return_to_target_app", AgentActionToolType.SEMANTIC, "回到目标应用", alwaysLoad = true, inputContract = "package_name", resultContract = "目标 App 恢复前台", progressLabel = "回到目标应用", fallbackTools = listOf("system.launch_app", "system.recents"), summary = "优先回到目标 App 而不是重新找路。"),
            AgentToolDescriptor("semantic.navigate_back", AgentActionToolType.SEMANTIC, "语义回退", alwaysLoad = true, inputContract = "hint", resultContract = "错误上下文回退", progressLabel = "语义回退", fallbackTools = listOf("system.back"), summary = "遇到跑偏场景时优先回退。"),
            AgentToolDescriptor("meta.wait", AgentActionToolType.META, "等待", concurrencySafe = true, permissionFamily = "wait", interruptBehavior = "block", inputContract = "optional wait duration", resultContract = "页面稳定或外部事件出现", progressLabel = "等待页面稳定", summary = "等待界面稳定或外部事件出现。"),
            AgentToolDescriptor("meta.finish", AgentActionToolType.META, "结束任务", irreversible = true, permissionFamily = "finish_task", inputContract = "summary", resultContract = "任务完成并输出结果", progressLabel = "结束任务", summary = "任务收口并输出结果。"),
            AgentToolDescriptor("meta.fail", AgentActionToolType.META, "终止任务", irreversible = true, permissionFamily = "fail_task", inputContract = "reason", resultContract = "任务终止", progressLabel = "终止任务", summary = "在不可恢复时终止任务。"),
        )

    fun descriptors(): List<AgentToolDescriptor> = descriptors

    fun names(): List<String> = descriptors.map { it.name }

    fun find(
        name: String,
    ): AgentToolDescriptor? = descriptors.firstOrNull { it.name == name }

    fun compactLines(
        limit: Int = 12,
    ): List<String> =
        descriptors.take(limit.coerceAtLeast(1)).map { descriptor ->
            buildString {
                append(descriptor.name)
                append(" | ").append(descriptor.title)
                if (descriptor.irreversible) append(" | irreversible")
                descriptor.summary.takeIf { it.isNotBlank() }?.let { append(" | ").append(it.take(72)) }
            }
        }
}
