package com.lmx.xiaoxuanagent.harness

data class HarnessScenario(
    val id: String,
    val title: String,
    val suite: String = "core",
    val persona: String = "operator",
    val maturity: String = "ga",
    val keywords: List<String>,
    val expectedProfileId: String? = null,
    val canonicalTasks: List<String> = emptyList(),
    val intentType: String = "",
    val priority: Int = 0,
    val tags: List<String> = emptyList(),
    val riskLevel: String = "medium",
    val requiredCapabilities: List<String> = emptyList(),
    val goldenKeywords: List<String> = emptyList(),
    val expectedStageHints: List<String> = emptyList(),
)

object HarnessScenarioRegistry {
    private val scenarios =
        listOf(
            HarnessScenario(
                id = "shopping_research",
                title = "商品搜索调研",
                suite = "commerce",
                persona = "personal",
                keywords = listOf("淘宝", "京东", "拼多多", "评价", "参数", "比价", "推荐", "商品"),
                canonicalTasks =
                    listOf(
                        "打开购物 App，看一下这款商品的评价和参数。",
                        "帮我比较这两个商品哪个更值得买。",
                ),
                intentType = "shopping_research",
                priority = 10,
                tags = listOf("commerce", "research"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "semantic_navigation"),
                goldenKeywords = listOf("评价", "参数", "详情"),
                expectedStageHints = listOf("enter_query", "browse_candidates", "inspect_information", "summarize"),
            ),
            HarnessScenario(
                id = "commerce_golden_paths",
                title = "高频电商 golden path",
                suite = "commerce",
                persona = "personal",
                keywords = listOf("淘宝", "京东", "拼多多", "闲鱼", "商品", "评价", "参数", "比价", "下单"),
                canonicalTasks =
                    listOf(
                        "打开淘宝搜一款适合通勤的双肩包，看看评价和参数。",
                        "打开京东搜一款自营手机，比较价格和评价。",
                        "打开拼多多找百亿补贴耳机，支付前交给我确认。",
                        "打开闲鱼搜二手显示器，联系卖家前交给我确认。",
                    ),
                intentType = "commerce_golden_path",
                priority = 10,
                tags = listOf("commerce", "golden_path", "handoff"),
                riskLevel = "high",
                requiredCapabilities = listOf("connected_app", "semantic_navigation", "human_final_confirmation"),
                goldenKeywords = listOf("golden_path", "商品", "评价", "参数", "支付前"),
                expectedStageHints = listOf("enter_query", "browse_candidates", "inspect_information", "confirm_handoff"),
            ),
            HarnessScenario(
                id = "local_service",
                title = "本地生活任务",
                suite = "lifestyle",
                persona = "personal",
                keywords = listOf("外卖", "奶茶", "美食", "酒店", "团购", "餐厅"),
                expectedProfileId = "meituan_assistant",
                canonicalTasks =
                    listOf(
                        "打开本地生活 App，看看附近适合点的奶茶。",
                        "帮我找一家评分高的餐厅。",
                ),
                intentType = "local_service",
                priority = 7,
                tags = listOf("lifestyle", "service"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "resume"),
                goldenKeywords = listOf("附近", "评分", "推荐"),
                expectedStageHints = listOf("enter_query", "browse_candidates", "summarize"),
            ),
            HarnessScenario(
                id = "navigation",
                title = "导航出行任务",
                suite = "mobility",
                persona = "personal",
                keywords = listOf("导航", "路线", "附近", "打车", "步行", "骑行", "开车"),
                expectedProfileId = "amap_assistant",
                canonicalTasks =
                    listOf(
                        "去浦东机场怎么走。",
                        "打开地图 App，规划去公司最快路线。",
                ),
                intentType = "navigation",
                priority = 9,
                tags = listOf("maps", "transport"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "semantic_navigation"),
                goldenKeywords = listOf("路线", "导航", "目的地"),
                expectedStageHints = listOf("enter_destination", "browse_candidates", "confirm_route"),
            ),
            HarnessScenario(
                id = "messaging",
                title = "通讯发送任务",
                suite = "communication",
                persona = "personal",
                keywords = listOf("微信", "发消息", "联系人", "聊天", "群聊"),
                expectedProfileId = "wechat_assistant",
                canonicalTasks =
                    listOf(
                        "去微信给韩威发一条晚安的消息。",
                        "帮我找到联系人并发消息确认今天的安排。",
                ),
                intentType = "messaging",
                priority = 9,
                tags = listOf("communication", "send"),
                riskLevel = "high",
                requiredCapabilities = listOf("resume", "semantic_navigation"),
                goldenKeywords = listOf("联系人", "会话", "发送"),
                expectedStageHints = listOf("find_conversation", "confirm_send"),
            ),
            HarnessScenario(
                id = "finance_payment_handoff",
                title = "支付宝支付前交接",
                suite = "finance",
                persona = "personal",
                keywords = listOf("支付宝", "账单", "生活缴费", "付款", "转账", "支付"),
                expectedProfileId = "alipay_assistant",
                canonicalTasks =
                    listOf(
                        "打开支付宝查一下最近账单。",
                        "打开支付宝准备生活缴费，支付前交给我确认。",
                    ),
                intentType = "payment_handoff",
                priority = 10,
                tags = listOf("finance", "handoff", "safety"),
                riskLevel = "critical",
                requiredCapabilities = listOf("connected_app", "safety_confirmation", "human_final_confirmation"),
                goldenKeywords = listOf("账单", "支付前", "确认", "handoff"),
                expectedStageHints = listOf("enter_query", "inspect_information", "confirm_handoff"),
            ),
            HarnessScenario(
                id = "content_research",
                title = "内容检索任务",
                suite = "content",
                persona = "personal",
                keywords = listOf("评论", "弹幕", "高赞", "最新一期", "最近一期", "视频", "文章", "笔记"),
                canonicalTasks =
                    listOf(
                        "打开 B 站，看下最新一期视频里点赞最高的评论。",
                        "帮我找目标作者最新内容并提炼重点。",
                ),
                intentType = "content_research",
                priority = 8,
                tags = listOf("content", "research"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "semantic_navigation"),
                goldenKeywords = listOf("评论", "高赞", "最新"),
                expectedStageHints = listOf("enter_query", "browse_candidates", "inspect_information", "summarize"),
            ),
            HarnessScenario(
                id = "approval_recovery",
                title = "恢复续跑任务",
                suite = "runtime",
                persona = "operator",
                keywords = listOf("继续", "恢复", "重新点", "回到上一步", "纠正", "重试"),
                canonicalTasks =
                    listOf(
                        "继续刚才中断的任务，并按我的纠错回到上一步重新处理。",
                        "从挂起状态恢复任务，先按提示纠正路径再继续。",
                    ),
                intentType = "approval_recovery",
                priority = 11,
                tags = listOf("recovery", "resume"),
                riskLevel = "high",
                requiredCapabilities = listOf("resume", "recovery"),
                goldenKeywords = listOf("恢复", "纠错", "继续"),
                expectedStageHints = listOf("resume", "browse_candidates", "inspect_information"),
            ),
            HarnessScenario(
                id = "routine_follow_up",
                title = "例行跟进任务",
                suite = "assistant_os",
                persona = "personal",
                keywords = listOf("提醒", "待办", "今天", "节奏", "跟进", "回顾"),
                canonicalTasks =
                    listOf(
                        "帮我看下今天还要跟进哪些事情，并整理重点。",
                        "检查待办和提醒，给我一个今天节奏建议。",
                    ),
                intentType = "routine_follow_up",
                priority = 6,
                tags = listOf("routine", "assistant_os"),
                riskLevel = "low",
                requiredCapabilities = listOf("structured", "fast_fallback"),
                goldenKeywords = listOf("跟进", "提醒", "节奏"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "generic_agent",
                title = "通用代理任务",
                suite = "general",
                persona = "operator",
                keywords = listOf("打开", "进入", "帮我", "看一下", "查一下"),
                canonicalTasks =
                    listOf(
                        "打开应用完成任务。",
                        "帮我进入目标 App 并找到对应入口。",
                ),
                intentType = "generic",
                priority = 5,
                tags = listOf("general"),
                riskLevel = "low",
                requiredCapabilities = listOf("fast_fallback"),
                goldenKeywords = listOf("打开", "进入"),
                expectedStageHints = listOf("browse_candidates", "summarize"),
            ),
            HarnessScenario(
                id = "assistant_onboarding",
                title = "助手引导配置",
                suite = "assistant_os",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("引导", "配置", "入口", "通知权限", "日历权限", "初始化"),
                canonicalTasks = listOf("帮我看下当前助手还缺哪些基础配置，并给出下一步建议。"),
                intentType = "assistant_onboarding",
                priority = 8,
                tags = listOf("assistant_os", "onboarding"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "routine"),
                goldenKeywords = listOf("配置", "权限", "入口"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "memory_governance",
                title = "记忆治理任务",
                suite = "assistant_os",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("记忆", "治理", "联系人", "偏好", "清理", "审计"),
                canonicalTasks = listOf("帮我检查当前个人记忆和治理状态，看下是否有需要整理的项。"),
                intentType = "memory_governance",
                priority = 8,
                tags = listOf("memory", "governance"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "memory_alignment"),
                goldenKeywords = listOf("记忆", "治理", "审计"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "provider_diagnostics",
                title = "Provider 诊断任务",
                suite = "runtime",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("provider", "路由", "诊断", "失败", "fallback", "planner"),
                canonicalTasks = listOf("帮我看下当前 provider/router 的状态和可能问题。"),
                intentType = "provider_diagnostics",
                priority = 8,
                tags = listOf("provider", "diagnostics"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "artifact_focus"),
                goldenKeywords = listOf("provider", "route", "fallback"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "session_viewer",
                title = "会话可视化任务",
                suite = "runtime",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("viewer", "timeline", "graph", "session", "trace"),
                canonicalTasks = listOf("帮我看下当前 session graph 和 timeline 的重点。"),
                intentType = "session_viewer",
                priority = 7,
                tags = listOf("viewer", "runtime"),
                riskLevel = "low",
                requiredCapabilities = listOf("structured", "artifact_focus"),
                goldenKeywords = listOf("session", "graph", "timeline"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "browser_research",
                title = "浏览器调研任务",
                suite = "research",
                persona = "personal",
                maturity = "beta",
                keywords = listOf("浏览器", "网页", "搜索", "对比", "资料", "调研"),
                canonicalTasks = listOf("打开浏览器，搜一下目标信息并整理重点。"),
                intentType = "browser_research",
                priority = 7,
                tags = listOf("browser", "research"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "semantic_navigation"),
                goldenKeywords = listOf("搜索", "网页", "重点"),
                expectedStageHints = listOf("enter_query", "browse_candidates", "inspect_information", "summarize"),
            ),
            HarnessScenario(
                id = "interrupt_governance",
                title = "打断治理任务",
                suite = "assistant_os",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("打断", "预算", "入口", "静默", "提醒", "share"),
                canonicalTasks = listOf("帮我看下当前打断预算和入口策略是否合理。"),
                intentType = "interrupt_governance",
                priority = 7,
                tags = listOf("interrupt", "governance"),
                riskLevel = "low",
                requiredCapabilities = listOf("structured", "routine"),
                goldenKeywords = listOf("预算", "入口", "静默"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "compensation_governance",
                title = "补偿治理任务",
                suite = "runtime",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("补偿", "回滚", "撤销", "事务", "审批"),
                canonicalTasks = listOf("帮我检查当前 session 的补偿计划、审批门和回滚依赖链。"),
                intentType = "compensation_governance",
                priority = 9,
                tags = listOf("compensation", "rollback"),
                riskLevel = "high",
                requiredCapabilities = listOf("structured", "recovery"),
                goldenKeywords = listOf("补偿", "审批", "依赖"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "scheduler_swarm",
                title = "调度协同任务",
                suite = "runtime",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("调度", "worker", "swarm", "公平", "lease", "graph"),
                canonicalTasks = listOf("帮我看下 parent-child session graph 和多 worker 调度是否健康。"),
                intentType = "scheduler_swarm",
                priority = 9,
                tags = listOf("scheduler", "swarm"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "artifact_focus"),
                goldenKeywords = listOf("graph", "worker", "lease"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "provider_learning",
                title = "Provider 学习路由任务",
                suite = "runtime",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("provider", "学习", "health", "route", "反馈"),
                canonicalTasks = listOf("帮我分析当前 provider health、学习路由得分和降权状态。"),
                intentType = "provider_learning",
                priority = 8,
                tags = listOf("provider", "learning"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "artifact_focus"),
                goldenKeywords = listOf("health", "score", "fallback"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "mobile_product_shell",
                title = "移动端 Product Shell 任务",
                suite = "assistant_os",
                persona = "personal",
                maturity = "beta",
                keywords = listOf("today", "inbox", "viewer", "shell", "手机", "助手"),
                canonicalTasks = listOf("帮我从手机超级助手视角看下 today/inbox/viewer/shell 是否成熟。"),
                intentType = "mobile_product_shell",
                priority = 8,
                tags = listOf("shell", "mobile"),
                riskLevel = "low",
                requiredCapabilities = listOf("structured", "routine"),
                goldenKeywords = listOf("today", "inbox", "viewer"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "safety_governance",
                title = "安全治理任务",
                suite = "assistant_os",
                persona = "operator",
                maturity = "beta",
                keywords = listOf("安全", "确认", "审批", "guardrail", "风险"),
                canonicalTasks = listOf("帮我检查当前助手的安全确认、人工接管和审批治理状态。"),
                intentType = "safety_governance",
                priority = 9,
                tags = listOf("safety", "governance"),
                riskLevel = "high",
                requiredCapabilities = listOf("structured", "recovery"),
                goldenKeywords = listOf("确认", "审批", "风险"),
                expectedStageHints = listOf("summarize"),
            ),
            HarnessScenario(
                id = "memory_personalization",
                title = "个性化记忆任务",
                suite = "assistant_os",
                persona = "personal",
                maturity = "beta",
                keywords = listOf("偏好", "记忆", "联系人", "个性化", "routine"),
                canonicalTasks = listOf("帮我结合个人记忆和偏好，看看今天最值得跟进的内容。"),
                intentType = "memory_personalization",
                priority = 7,
                tags = listOf("memory", "personalization"),
                riskLevel = "medium",
                requiredCapabilities = listOf("structured", "memory_alignment"),
                goldenKeywords = listOf("记忆", "偏好", "跟进"),
                expectedStageHints = listOf("summarize"),
            ),
        )

    fun all(): List<HarnessScenario> = scenarios

    fun match(
        task: String,
        profileId: String,
    ): HarnessScenario? {
        val normalizedTask = task.trim()
        if (normalizedTask.isBlank()) return null
        return scenarios.maxByOrNull { scenario ->
            scenario.keywords.fold(
                if (scenario.expectedProfileId == profileId) 8 else 0,
            ) { acc, keyword ->
                when {
                    normalizedTask.equals(keyword, ignoreCase = true) -> acc + 6
                    normalizedTask.contains(keyword, ignoreCase = true) -> acc + 3
                    else -> acc
                }
            }
        }?.takeIf { scenario ->
            scenario.keywords.any { normalizedTask.contains(it, ignoreCase = true) } ||
                scenario.expectedProfileId == profileId
        }
    }
}
